# 储存数据集的路径
data:
  dataset: 'MIMII'
  pkl_file_path: './data/data.pkl'
  batch_size: 32

# 划分数据
spilt:
  testsize: 0.2
  random_state: 42
# 模型
model:
  model: 'CNN'
  input_dim: 13
  hidden_dim: 128
# 训练参数
train:
  epochs: 20
  loss: 'CrossEntropyLoss'
optimizer:
  optim: 'Adam'
  lr: 0.0001